services:
  vraksha:
    image: vraksha-runtime:latest
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/vraksha
    env_file:
      - .env.local
    stdin_open: true
    tty: true